[project]
name = "coveralls"
version = "4.1.0"
description = "Show coverage stats online via coveralls.io"
readme = "README.rst"
requires-python = ">=3.10"

authors = [
    { name="Kevin James", email="coveralls-python@thekev.in" },
]
license = "MIT"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development :: Testing",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "coverage[toml] (>=6.3,<8.0)",
    "requests (>=1.0.0,<3.0.0)",
    "typer (>=0.12.0,<1.0.0)"
]

[project.urls]
Changelog = "https://github.com/TheKevJames/coveralls-python/blob/master/CHANGELOG.md"
Docs = "https://coveralls-python.rtfd.io/"
Repository = "https://github.com/TheKevJames/coveralls-python"

[project.scripts]
coveralls = "coveralls.cli:main"
python-coveralls = "coveralls.cli:main"

[project.optional-dependencies]
yaml = ["pyyaml (>=3.10,<7.0)"]

[dependency-groups]
dev = [
    "pytest ==9.1.1",
    "responses ==0.26.2"
]
docs = ["sphinx ==9.1.0; python_version >='3.12'"]

[tool.poetry]
packages = [
    { include = "coveralls" },
]

[tool.pytest.ini_options]
# addopts = "-Werror"
filterwarnings = [
    "error",
    # co_lnotab deprection on py3.12+ is fixed in coverage v7.1
    "ignore:co_lnotab is deprecated, use co_lines instead:DeprecationWarning",
]

[tool.tox]
env_list = [
    { product = [["py310", "py311", "py312", "py313", "py314", "pypy3"], ["cov6", "cov7"], ["default", "pyyaml"]] },
]

[tool.tox.env_run_base]
pass_env = ["*"]
use_develop = true
deps = [
    "responses==0.25.8",
    "pytest==9.0.2",
    { replace = "if", condition = "factor.pyyaml", then = ["PyYAML>=3.10,<7.0"], extend = true },
    { replace = "if", condition = "factor.cov6", then = ["coverage[toml]>=6.0,<7.0"], extend = true },
    { replace = "if", condition = "factor.cov7", then = ["coverage[toml]>=7.0,<8.0"], extend = true },
]
commands = [
    ["coverage", "run", "--branch", "--source=coveralls", "-m", "pytest", "tests/"],
    ["coverage", "report", "-m"],
]

[tool.tox.env.upload]
deps = ["coverage[toml]>=7.0,<8.0"]
commands = [["coveralls", "--verbose"]]

[tool.tox.gh-actions]
python = """
3.10: py310, upload
3.11: py311, upload
3.12: py312, upload
3.13: py313, upload
3.14: py314, upload
"""

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
