import importlib.metadata
import logging
import sys
from collections.abc import Callable
from typing import Annotated
from typing import Any

import typer
from typer._click.exceptions import ClickException
from typer._click.exceptions import UsageError

from .api import Coveralls


log = logging.getLogger('coveralls')
# One template for every "X is deprecated, use Y" warning so the deprecated
# option aliases and the deprecated verb flags cannot drift apart.
DEPRECATION_TEMPLATE = (
    '%s is deprecated and will be removed in a future release; use %s instead.'
)
APP_HELP = """Publish coverage results online via coveralls.io.

This tool makes custom reports for data generated by coverage.py package and
sends it to the coveralls.io service API.

All Python files in your coverage analysis are posted to this service along
with coverage stats, so please make sure you're not ruining your own security!

Run without a command to collect and submit coverage; see commands below.
"""
DEBUG_HELP = (
    "Don't send anything, just output json to stdout. Also forces verbose "
    'output. Please use debug mode when submitting bug reports.'
)


app = typer.Typer(
    add_completion=True,
    context_settings={'help_option_names': ['-h', '--help']},
    help=APP_HELP,
)


def _show_version(value: bool) -> None:
    if value:
        typer.echo(importlib.metadata.version('coveralls'))
        raise typer.Exit()


def _configure_logging(*, verbose: bool) -> None:
    # Guard against duplicate handlers: main() may be invoked more than once in
    # the same process (tests, library reuse) and each StreamHandler would
    # otherwise stack up and multiply the output.
    if not log.handlers:
        log.addHandler(logging.StreamHandler())
    log.setLevel(logging.DEBUG if verbose else logging.INFO)


def _resolve_deprecated(
    new: str | None, old: str | None,
    new_flag: str, old_flag: str,
) -> str | None:
    """Prefer the canonical value, warning when the deprecated flag is used."""
    if old is None:
        return new
    log.warning(DEPRECATION_TEMPLATE, old_flag, new_flag)
    return new if new is not None else old


def _warn_deprecated_verb(old_flag: str, new_command: str) -> None:
    """Warn that an action flag is superseded by a subcommand."""
    log.warning(DEPRECATION_TEMPLATE, old_flag, new_command)


def _make_coveralls(
    *, token_required: bool,
    service_name: str | None = None, service: str | None = None,
    rcfile: str | None = None,
    base_dir: str | None = None, basedir: str | None = None,
    src_dir: str | None = None, srcdir: str | None = None,
    host: str | None = None, skip_ssl_verify: bool | None = None,
    parallel: bool | None = None,
    timeout: float | None = None,
    connect_timeout: float | None = None, read_timeout: float | None = None,
) -> Coveralls:
    # pylint: disable=too-many-arguments
    # Modifiers not exposed by a command default to None; resolve() drops unset
    # ones so nothing clobbers env/config. An explicit value (incl. a False
    # from --no-parallel) overrides.
    service_name = _resolve_deprecated(
        service_name, service, '--service-name', '--service',
    )
    base_dir = _resolve_deprecated(
        base_dir, basedir, '--base-dir', '--basedir',
    )
    src_dir = _resolve_deprecated(src_dir, srcdir, '--src-dir', '--srcdir')

    overrides: dict[str, Any] = {
        'rcfile': rcfile,
        'service_name': service_name,
        'base_dir': base_dir,
        'src_dir': src_dir,
        'host': host,
        'parallel': parallel,
        'skip_ssl_verify': skip_ssl_verify,
        'timeout': timeout,
        'connect_timeout': connect_timeout,
        'read_timeout': read_timeout,
    }
    return Coveralls(token_required, **overrides)


def _run_action(action: Callable[[], None]) -> None:
    try:
        action()
    except KeyboardInterrupt:  # pragma: no cover
        log.info('Aborted')
    except Exception as e:
        log.exception('Error running coveralls: %s', e)
        sys.exit(1)


def _action_submit(coverallz: Coveralls, merge: str | None) -> None:
    if merge:
        coverallz.merge(merge)
    log.info('Submitting coverage to coveralls.io...')
    result = coverallz.wear()
    log.info('Coverage submitted!')
    log.debug(result)
    if result:
        log.info(result.get('message'))
        log.info(result.get('url'))


def _action_save(coverallz: Coveralls, merge: str | None, path: str) -> None:
    if merge:
        coverallz.merge(merge)
    log.info('Write coverage report to file...')
    coverallz.save_report(path)


# merge is a no-op for upload/finish (their payloads ignore the merged data),
# but the old flat CLI ran it before every action, so the deprecated
# --submit/--finish paths pass it for identical dispatch.
def _action_upload(
    coverallz: Coveralls, path: str, merge: str | None = None,
) -> None:
    if merge:
        coverallz.merge(merge)
    with open(path) as report_file:
        coverallz.submit_report(report_file.read())


def _action_finish(coverallz: Coveralls, merge: str | None = None) -> None:
    if merge:
        coverallz.merge(merge)
    log.info('Finishing parallel jobs...')
    coverallz.parallel_finish()
    log.info('Done')


def _action_debug(coverallz: Coveralls, merge: str | None) -> None:
    if merge:
        coverallz.merge(merge)
    log.info('Testing coveralls-python...')
    coverallz.wear(dry_run=True)


# Shared modifier specs, defined once. Typer still needs each command to list
# the options it exposes, so the per-command signatures repeat; these single
# definitions keep the option names, help and deprecation status from drifting.
_ServiceName = Annotated[
    str | None,
    typer.Option(
        '--service-name',
        help='Provide an alternative service name to submit.',
    ),
]
_Service = Annotated[
    str | None,
    typer.Option(
        '--service', hidden=True, help='Deprecated alias for --service-name.',
    ),
]
_Rcfile = Annotated[
    str | None,
    typer.Option(
        '--rcfile',
        help='Specify the coverage.py config file (default: auto-discovered).',
    ),
]
_BaseDir = Annotated[
    str | None,
    typer.Option(
        '--base-dir',
        help='Base directory that is removed from reported paths.',
    ),
]
_Basedir = Annotated[
    str | None,
    typer.Option(
        '--basedir', hidden=True, help='Deprecated alias for --base-dir.',
    ),
]
_SrcDir = Annotated[
    str | None,
    typer.Option(
        '--src-dir', help='Source directory added to reported paths.',
    ),
]
_Srcdir = Annotated[
    str | None,
    typer.Option(
        '--srcdir', hidden=True, help='Deprecated alias for --src-dir.',
    ),
]
_Merge = Annotated[
    str | None,
    typer.Option('--merge', help='Merge report from file when submitting.'),
]
_Parallel = Annotated[
    bool | None,
    typer.Option(
        '--parallel/--no-parallel',
        help='Submit as one of several parallel jobs to be merged.',
    ),
]
_Host = Annotated[
    str | None,
    typer.Option('--host', help='Coveralls API host base URL.'),
]
_SkipSslVerify = Annotated[
    bool | None,
    typer.Option(
        '--skip-ssl-verify/--no-skip-ssl-verify',
        help='Skip verification of the SSL certificate of the host.',
    ),
]
_Verbose = Annotated[
    bool,
    typer.Option(
        '-v', '--verbose',
        help='Print extra info, always enabled when debugging.',
    ),
]
_Timeout = Annotated[
    float | None,
    typer.Option(
        '--timeout',
        help='Connect and read timeout, in seconds (default: 10/60).',
    ),
]
_ConnectTimeout = Annotated[
    float | None,
    typer.Option(
        '--connect-timeout', help='Connect timeout, in seconds (default: 10).',
    ),
]
_ReadTimeout = Annotated[
    float | None,
    typer.Option(
        '--read-timeout', help='Read timeout, in seconds (default: 60).',
    ),
]
_Version = Annotated[
    bool | None,
    typer.Option(
        '--version', callback=_show_version, is_eager=True,
        help='Display the version and exit.',
    ),
]

# Deprecated action flags kept as hidden aliases on the default command so CI
# pipelines keep working: they dispatch to the matching subcommand and warn.
_Output = Annotated[
    str | None,
    typer.Option(
        '--output', hidden=True,
        help='Deprecated alias for the save command.',
    ),
]
_Submit = Annotated[
    str | None,
    typer.Option(
        '--submit', hidden=True,
        help='Deprecated alias for the upload command.',
    ),
]
_Finish = Annotated[
    bool,
    typer.Option(
        '--finish', hidden=True,
        help='Deprecated alias for the finish command.',
    ),
]

_File = Annotated[str, typer.Argument(help='Coverage report file path.')]


@app.callback(invoke_without_command=True)
def coveralls(
    ctx: typer.Context,
    service_name: _ServiceName = None,
    service: _Service = None,
    rcfile: _Rcfile = None,
    base_dir: _BaseDir = None,
    basedir: _Basedir = None,
    src_dir: _SrcDir = None,
    srcdir: _Srcdir = None,
    host: _Host = None,
    skip_ssl_verify: _SkipSslVerify = None,
    verbose: _Verbose = False,
    timeout: _Timeout = None,
    connect_timeout: _ConnectTimeout = None,
    read_timeout: _ReadTimeout = None,
    merge: _Merge = None,
    parallel: _Parallel = None,
    output: _Output = None,
    submit: _Submit = None,
    finish_flag: _Finish = False,
    version: _Version = None,
) -> None:
    # pylint: disable=too-many-arguments,too-many-positional-arguments
    # pylint: disable=too-many-locals
    """Collect coverage and submit it to coveralls.io."""
    _ = version
    verb_flags = [
        flag for flag, given in (
            ('--finish', finish_flag),
            ('--output', output is not None),
            ('--submit', submit is not None),
        ) if given
    ]

    # This also runs as the group callback for every subcommand. A deprecated
    # action flag paired with a subcommand is a usage error; other modifiers
    # before a subcommand are ignored (the subcommand owns its options) and
    # configures its own logging, so there is nothing else to do here.
    if ctx.invoked_subcommand is not None:
        if verb_flags:
            raise UsageError(
                f'{verb_flags[0]} cannot be combined with the '
                f'{ctx.invoked_subcommand!r} command.',
            )
        return

    _configure_logging(verbose=verbose)
    if len(verb_flags) > 1:
        raise UsageError(
            f'{verb_flags[0]} cannot be combined with {verb_flags[1]}.',
        )

    modifiers: dict[str, Any] = {
        'service_name': service_name, 'service': service, 'rcfile': rcfile,
        'base_dir': base_dir, 'basedir': basedir, 'src_dir': src_dir,
        'srcdir': srcdir, 'host': host, 'skip_ssl_verify': skip_ssl_verify,
        'parallel': parallel, 'timeout': timeout,
        'connect_timeout': connect_timeout, 'read_timeout': read_timeout,
    }

    if finish_flag:
        _warn_deprecated_verb('--finish', 'coveralls finish')
        coverallz = _make_coveralls(token_required=True, **modifiers)
        _run_action(lambda: _action_finish(coverallz, merge))
    elif output is not None:
        _warn_deprecated_verb('--output', 'coveralls save FILE')
        coverallz = _make_coveralls(token_required=False, **modifiers)
        _run_action(lambda: _action_save(coverallz, merge, output))
    elif submit is not None:
        _warn_deprecated_verb('--submit', 'coveralls upload FILE')
        coverallz = _make_coveralls(token_required=True, **modifiers)
        _run_action(lambda: _action_upload(coverallz, submit, merge))
    else:
        coverallz = _make_coveralls(token_required=True, **modifiers)
        _run_action(lambda: _action_submit(coverallz, merge))


@app.command()
def finish(
    host: _Host = None,
    skip_ssl_verify: _SkipSslVerify = None,
    verbose: _Verbose = False,
    timeout: _Timeout = None,
    connect_timeout: _ConnectTimeout = None,
    read_timeout: _ReadTimeout = None,
) -> None:
    """Notify coveralls.io that all parallel jobs are done."""
    _configure_logging(verbose=verbose)
    coverallz = _make_coveralls(
        token_required=True, host=host, skip_ssl_verify=skip_ssl_verify,
        timeout=timeout, connect_timeout=connect_timeout,
        read_timeout=read_timeout,
    )
    _run_action(lambda: _action_finish(coverallz))


@app.command()
def upload(
    file: _File,
    host: _Host = None,
    skip_ssl_verify: _SkipSslVerify = None,
    verbose: _Verbose = False,
    timeout: _Timeout = None,
    connect_timeout: _ConnectTimeout = None,
    read_timeout: _ReadTimeout = None,
) -> None:
    """Upload a previously generated coverage report FILE."""
    _configure_logging(verbose=verbose)
    coverallz = _make_coveralls(
        token_required=True, host=host, skip_ssl_verify=skip_ssl_verify,
        timeout=timeout, connect_timeout=connect_timeout,
        read_timeout=read_timeout,
    )
    _run_action(lambda: _action_upload(coverallz, file))


@app.command()
def save(
    file: _File,
    service_name: _ServiceName = None,
    service: _Service = None,
    rcfile: _Rcfile = None,
    base_dir: _BaseDir = None,
    basedir: _Basedir = None,
    src_dir: _SrcDir = None,
    srcdir: _Srcdir = None,
    host: _Host = None,
    skip_ssl_verify: _SkipSslVerify = None,
    verbose: _Verbose = False,
    timeout: _Timeout = None,
    connect_timeout: _ConnectTimeout = None,
    read_timeout: _ReadTimeout = None,
    merge: _Merge = None,
    parallel: _Parallel = None,
) -> None:
    # pylint: disable=too-many-arguments,too-many-positional-arguments
    # pylint: disable=too-many-locals
    """Build the coverage report and write it to FILE without sending it."""
    _configure_logging(verbose=verbose)
    # --parallel is accepted although nothing is sent: it is baked into the
    # written JSON so a later `coveralls upload` submits the job as parallel.
    coverallz = _make_coveralls(
        token_required=False, service_name=service_name, service=service,
        rcfile=rcfile, base_dir=base_dir, basedir=basedir, src_dir=src_dir,
        srcdir=srcdir, host=host, skip_ssl_verify=skip_ssl_verify,
        parallel=parallel, timeout=timeout, connect_timeout=connect_timeout,
        read_timeout=read_timeout,
    )
    _run_action(lambda: _action_save(coverallz, merge, file))


@app.command(help=DEBUG_HELP)
def debug(
    service_name: _ServiceName = None,
    service: _Service = None,
    rcfile: _Rcfile = None,
    base_dir: _BaseDir = None,
    basedir: _Basedir = None,
    src_dir: _SrcDir = None,
    srcdir: _Srcdir = None,
    host: _Host = None,
    skip_ssl_verify: _SkipSslVerify = None,
    timeout: _Timeout = None,
    connect_timeout: _ConnectTimeout = None,
    read_timeout: _ReadTimeout = None,
    merge: _Merge = None,
    parallel: _Parallel = None,
) -> None:
    # pylint: disable=too-many-arguments,too-many-positional-arguments
    # pylint: disable=too-many-locals
    # debug always forces verbose and sends nothing, so it omits its own
    # (always-on, thus meaningless) --verbose flag.
    _configure_logging(verbose=True)
    coverallz = _make_coveralls(
        token_required=False, service_name=service_name, service=service,
        rcfile=rcfile, base_dir=base_dir, basedir=basedir, src_dir=src_dir,
        srcdir=srcdir, host=host, skip_ssl_verify=skip_ssl_verify,
        parallel=parallel, timeout=timeout, connect_timeout=connect_timeout,
        read_timeout=read_timeout,
    )
    _run_action(lambda: _action_debug(coverallz, merge))


def main(argv: list[str] | None = None) -> None:
    command = typer.main.get_command(app)
    try:
        command.main(args=argv, prog_name='coveralls', standalone_mode=False)
    # ClickException comes from typer's vendored click (not a standalone dep);
    # it is the concrete base typer raises for usage errors -- bad option,
    # missing argument, our guardrail UsageErrors, etc. Render them as a clean
    # message plus exit code instead of dumping a traceback.
    except ClickException as e:
        e.show()
        raise SystemExit(e.exit_code) from e
