name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v6.0.2
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v5.0.0
        with:
          fail-on-severity: low
          fail-on-scopes: runtime,development,unknown
          license-check: false
          vulnerability-check: true
          comment-summary-in-pr: on-failure
          show-openssf-scorecard: false
          show-patched-versions: true
